### ISSUE TITLE
Add support

### ISSUE THREAD

**Issue by jacobhallgren** [SpoturDeal/MMM-Domoticz#1]
Can you please add support for:

Domoticz security panel status: Armed, Disarmed etc.
Custom sensor: TEXT

**Comment by SpoturDeal** [comment]
I can add security panel for you. However I'm not using the security panel could you please from your system the data for the security panel

`YOUR DOMOTICS IP ADDRESS /json.htm?type=devices&filter=all&used=true&order=Name`

it should give something similar to this

```
 {
         "Data" : "Off",
         "Description" : "Blue light",
         "Favorite" : 0,
         "LastUpdate" : "2018-08-25 20:48:16",
         "Name" : "Switch blue",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "Off",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "5"
      },

```
I i have the security part I can add  it

**Comment by jacobhallgren** [comment]
20 |  
-- | --
AddjMulti | 1
AddjMulti2 | 1
AddjValue | 0
AddjValue2 | 0
BatteryLevel | 255
CustomImage | 0
Data | "Normal"
Description | ""
Favorite | 1
HardwareID | 1
HardwareName | "Domoticz Internal"
HardwareType | "Domoticz Internal interface"
HardwareTypeVal | 67
HaveDimmer | false
HaveGroupCmd | false
HaveTimeout | false
ID | "148702"
LastUpdate | "2018-10-09 16:51:56"
MaxDimLevel | 0
Name | "Domoticz Security Panel"
Notifications | "false"
PlanID | "0"


Data can be three things: Normal, Arm Away or Armed Home I think it would be nice to make a if statement for the Normal and change it to show Disarmed.

**Comment by SpoturDeal** [comment]
Support for alarm added today
