### ISSUE TITLE
Space on display

### ISSUE THREAD

**Issue by Doudy** [SpoturDeal/MMM-Domoticz#13]
How do I insert a space between 'Wind direction' and 'SSE - 169°' ?
Current display: 'Wind directionS-169°'
Desired display: 'Wind direction S-169°'
Thanks

**Comment by SpoturDeal** [comment]
Hello @Doudy 

You can't add the space in the settings.

I have just uploaded a new version with a forced space (nbsp) between the device Name and the value.
I didn't test if it works properly when the module is placed on the left side of the screen. For right side it looks OKay.

Let me know if it helped.

**Comment by Doudy** [comment]
There is a problem
**Nothing is displayed**
I have rename my old directory as Old-MMM-Domoticz
I have execute git clone https://github.com/spoturdeal/MMM-Domoticz.git

At my old directory i have:
`.git
domoticz.js
LICENSE
mmm-domoticz.png
README.md`

In your latest version, I have:
`.git
domoticz.css
domoticz.less
LICENSE
MMM_Domoticz.js
node_helper.js
README.md
screendomoticz.png
String.format.js`

**Comment by SpoturDeal** [comment]
_Are you sure you were in the Directory ~/MagicMirror/modules when you used clone?
Otherwise your module is in Old-MMM-Domoticz/MMM-Domoticz_

The files in your latest directory are good.
can you go to the directory

```
cd MagicMirros/modules/MMM-Domoticz
git pull
pm2 restart MagicMirror 
```
If you didn't install pm2 then 
```
sudo reboot now
 ```

At my mirror the module is working properly

**Comment by Doudy** [comment]
I do
`~/MagicMirror/modules/MMM-Domoticz $ git pull
Déjà à jour.
`
And at config.js i have change line 
`module: 'MMM-Domoticz/domoticz', //folder`
with
`module: 'MMM-Domoticz', //folder`
now i have
`Loading Domoticz data...`
but no data displayed

**Comment by SpoturDeal** [comment]
Better start new again 

```
cd MagicMirros/modules
sudo rm MMM-Domoticz
```
Please read the [README](https://github.com/SpoturDeal/MMM-Domoticz/blob/master/README.md) file for proper installation and setting up the config file.

Installation
Navigate into your MagicMirror's modules folder and execute 
```
git clone https://github.com/spoturdeal/MMM-Domoticz.git.
```

**Comment by Doudy** [comment]
I found the problem 👍:

I have not add the new module inside config.js
I had not adapted apiBase and apiPort in MMM-Domoticz-js
