### ISSUE TITLE
Loading Domoticz data... 

### ISSUE THREAD

**Issue by MadhunterNL** [SpoturDeal/MMM-Domoticz#16]
Hi,

Probably I am not using the correct api login but where can I find the correct apiUser and apiPW. I have made a Domoticz account. In my Domoticz server I see MyInstaceID, an apiKey and a password. When I login in my.domoticz.com in instance settings I can see a username and a password.

Which one do I use and do I have to use a login when my Domoticz server is in the same network as the mirror?

Thanks in advance,
Iwan

**Comment by SpoturDeal** [comment]
The apiUser en apiPW are you login credentials for the website of your
Domoticz device .

It has nothing to with Domoticz.com


Op do 18 jul. 2019 22:48 schreef MadhunterNL <notifications@github.com>:

**Comment by MadhunterNL** [comment]
Feeling dumb here.... still no luck in getting it to work.

I filled in my internal IP address, my username and my password, still getting no data. By the way, within my network I do not have to login.

Is there some logging I can check? It must be making a connection now....how can I check the connection is okay?

**Comment by SpoturDeal** [comment]
Are you using the proper port number :8080 or :8088
If you don't need a password try to leave user and password empty.

Look at the URL if you are accessing from a pc what the proper IP and port
number are.

Good luck

Grtz

Carl

Op za 20 jul. 2019 12:51 schreef MadhunterNL <notifications@github.com>:

**Comment by MadhunterNL** [comment]
Ahhhh Carl, that is the solution: leaving the user and password empty. I tried it before with removing the lines apiUser and apiPw, that did not work. Leaving the lines empty did it.

Thanks for your help!

**Comment by SpoturDeal** [comment]
Be aware that using Domoticz without user and password makes it vulnerable
to unqualified access by anyone on your WIFi network.

It is better to use an username and password.

Op za 20 jul. 2019 13:00 schreef MadhunterNL <notifications@github.com>:

**Comment by zodracom** [comment]
So! i've got the same problem. tried everything, nothing works. Please can you check what i'm doing wrong?

i tried to change the port, leave user en password empty, use the external IP adres.

when i go to  http://192.168.2.35:8080/json.htm?type=devices&used=true&order=Name everything works and i see the vallue's of my domoticz system in plain text. 

my internal network is "password free" on network 192.168.2.*, so i tried with and without a password. 

Can someone help me? is there something wrong in the code below?

`{
	module: "MMM-Domoticz",
	position: "top_right",   // see mirror setting for options
	config: {          
		updateInterval: 45, // every 45 seconds
		apiBase:'192.168.2.35',
		apiPort: 8080,
		apiUser: "user",
    		apiPw: "password",
		moduleTitle: "My smart home by Domoticz",
		energyTitle: "Energy used by",
		batteryTitle: "Battery level",
		coTitle: "CO2 level",
		blindsTitle: "Blinds",
		energyNow: "Currently using",
		energyTotal: "Energy used",
		energyToday: "Energy used today",
		batteryThreshold: 20,
    		coThreshold: 650,
		subMenus: true,
		smartMeter: false,
		smartMeterOffset: 0,
		showItems: ['temperature','energy','battery','co','blinds','humidity','baro','usage','voltage','alarm','sensor','pulse','meter','rain'],   
		excludeDevices: ['none','add your own'],  // Device that will not be shown
		onlyShowExcluded: false, // if true only exluded devices are shown
		textWhite: false,
		alarmOffLabel: "Disabled",
		groupSensors: false
	}
},`

**Comment by zodracom** [comment]
even with password and username in the link it works:

http://user:password@192.168.2.35:8080/json.htm?type=devices&used=true&order=Name

**Comment by SpoturDeal** [comment]
Hello @zodracom 
I have checked your config file and it looks OK.
Do you get an error message or just Loading ...?

I am not in the country at this moment. It might take two more weeks before i can look into any issues.

**Comment by zodracom** [comment]
Hi. I get the "loading domoticz...." on my screen. But it never loads. I checked my log in Domoticz, it says "incomming connection from 292.168.2.19, so the mmm tries to log in, but no succes

**Comment by MadhunterNL** [comment]
> Hi. I get the "loading domoticz...." on my screen. But it never loads. I checked my log in Domoticz, it says "incomming connection from 292.168.2.19, so the mmm tries to log in, but no succes

Does your password contain special punction marks like for example '!'? That was a problem for me once trying to log in in Domoticz.

**Comment by SpoturDeal** [comment]
The username and the password should be exact the same as you enter them to
login to Domoticz.

All between "

No special characters

Op do 22 aug. 2019 14:29 schreef MadhunterNL <notifications@github.com>:

**Comment by zodracom** [comment]
yes, they are exact the same. 

i'm running Domoticz Version: 4.10717.

i tried to make a new user, still no good connection. the password and username are normal, no special punction marks. for example user: pi, password: password. stil no connection. the IP adress and port are okay. 

i even tried my external IP adress, to enter the domoticz from outside. 

when surfing to the IP, i can login with my user and password, so i'm sure they are correct

**Comment by zodracom** [comment]
when i go to `http://user:password@192.168.2.35:8080/json.htm?type=devices&used=true&order=Name` i get this:

[Domoticz Json.txt](https://github.com/SpoturDeal/MMM-Domoticz/files/3554827/Domoticz.Json.txt)

**Comment by SpoturDeal** [comment]
Is your Magic mirror in the same IP range?

Op do 29 aug. 2019 11:28 schreef zodracom <notifications@github.com>:

**Comment by zodracom** [comment]
yes. Domoticz @ 192.168.2.35 and Magic Mirror @ 192.168.2.25

**Comment by SpoturDeal** [comment]
What  does your logs show?

**Comment by SpoturDeal** [comment]
Due to the great number of users where the module is working I think the issue is in your network.
I will close this issue

**Comment by zodracom** [comment]
> What does your logs show?


2019-09-05 22:44:53.006 Status: Incoming connection from: 192.168.2.25

no further info or errors. Domoticz keeps loading on MM2

**Comment by mbreevoort** [comment]
@zodracom 
It did not work for me with the admin user (basic authentication). Created a new user (Setup -> More options -> Edit Users.
![image](https://user-images.githubusercontent.com/3529964/82362435-a367df00-9a0c-11ea-9016-ba77fe01a203.png)
Added the user and click set devices and added some devices (try to add one temperature device first, when I add gas usage it stops working). With this user I see Domoticz on the raspberry pi.

Hope this will help someone.

**Comment by art212** [comment]
Hi!
I like your program "Domoticz-module to  MagicMirror" and it makes my life a lot easier :) Can you tell me how I could delete this element in the code? (in Attachment)

![Inkednnj_LI](https://user-images.githubusercontent.com/47208050/103212065-2984c600-490a-11eb-9b64-807205039960.jpg)

greetings!
