### ISSUE TITLE
Can I exclude certain values of the P1 meter?

### ISSUE THREAD

**Issue by MadhunterNL** [SpoturDeal/MMM-Domoticz#17]
I want to show a few values from my P1 meter, but not all of them. Is it possible to exclude certain values?

Now it shows everything and I want for example only 'energyNow, energyToday, gasToday' to be shown.

I tried to put those values in excludeDevices, but that did not work.

**Comment by SpoturDeal** [comment]
At this moment only all p1 Meter Info is shown.
To break it up I have to add parameters to the script.

The script has already a lot of parameters and sometimes too much is for
many user too much to set up

Op za 20 jul. 2019 13:46 schreef MadhunterNL <notifications@github.com>:
