### ISSUE TITLE
P1 meter not showing negative value

### ISSUE THREAD

**Issue by MadhunterNL** [SpoturDeal/MMM-Domoticz#18]
Sorry to bother you again, but the value energyNow is due too solar panels sometimes negative in my situation. 

In Domoticz this value shows up for example as -640 watt, in the module the value is 0,0.

Is this fixable?

**Comment by MadhunterNL** [comment]
In addition to that, there is also a return value. See example. Would be great to include this value as well!

![return_value](https://user-images.githubusercontent.com/41516403/61579050-49eb0700-ab00-11e9-9da7-33fd6aad0c7a.png)

**Comment by SpoturDeal** [comment]
I am out of the country for two weeks
Will look into it later.

Op za 20 jul. 2019 15:09 schreef MadhunterNL <notifications@github.com>:

**Comment by SpoturDeal** [comment]
In my own system I am not returning any energy, so I am not able to add this to the module

**Comment by gehoel** [comment]
> 
> 
> Sorry to bother you again, but the value energyNow is due too solar panels sometimes negative in my situation.
> 
> In Domoticz this value shows up for example as -640 watt, in the module the value is 0,0.
> 
> Is this fixable?

Hello MadhunterNL,

I have made an Fork of this Module to make the negative values visible.
please give it a try.
[](https://github.com/gehoel/MMM-Domoticz)

Kind regards,
Bart

**Comment by MadhunterNL** [comment]
Hi Bart,

Thanks for that. How do i update my MMM-Domoticz module with your changes? Simply copy them into the domoticz directory?

And I need a sunny day here in the Netherlands ;-) You probably can not help with that….

**Comment by gehoel** [comment]
> 
> 
> Hi Bart,
> 
> Thanks for that. How do i update my MMM-Domoticz module with your changes? Simply copy them into the domoticz directory?
> 
> And I need a sunny day here in the Netherlands ;-) You probably can not help with that….

Hello,

the easiest way would be to remove the one you already have and then install my MMM-Domoticz module.
I'm still working on your other question for hiding items. (I want it to)

greetings,
Bart

**Comment by MadhunterNL** [comment]
Ok, installed. Waiting for the sun to arrive...

**Comment by MadhunterNL** [comment]
This works perfect!! Thanks for that. I hope that you succeed in hiding items. That would make it complete for me.
![teruglevering](https://user-images.githubusercontent.com/41516403/66996495-1f91f100-f0d1-11e9-93d3-51c4b9c6b3a0.png)

**Comment by gehoel** [comment]
> 
> 
> This works perfect!! Thanks for that. I hope that you succeed in hiding items. That would make it complete for me.
> ![teruglevering](https://user-images.githubusercontent.com/41516403/66996495-1f91f100-f0d1-11e9-93d3-51c4b9c6b3a0.png)

I have made some changes and you should be able to hide items after you update to the newest release.

**Comment by MadhunterNL** [comment]
Nice! Works great! Really happy with that. Thank you for this!
![domoticz](https://user-images.githubusercontent.com/41516403/67017474-24b76600-f0fa-11e9-965c-aed2a031be67.png)
