### ISSUE TITLE
onlyShowExcluded = true, not working

### ISSUE THREAD

**Issue by flopp999** [SpoturDeal/MMM-Domoticz#19]
I want to show only one device from my DZ.

I write the name of the device in excludeDevices and set onlyShowExcluded to true, but I do get all my devices.

If I change onlyShowExcluded to false it will exclude my the device from excludeDevices .

**Comment by SpoturDeal** [comment]
I am sorry without at depersonalized example of your config setting for this module I am not able to look into it.

**Comment by flopp999** [comment]
```
{
	module: "MMM-Domoticz",
	position: "top_right",   // see mirror setting for options
	config: {          
		updateInterval: 45, // every 45 seconds
		apiBase: '192.168.100.176',
		apiPort: 8080,
		apiUser: "",
    		apiPw: "",
		moduleTitle: "My smart home by Domoticz",
		energyTitle: "Energy used by",
		batteryTitle: "Battery level",
		coTitle: "CO2 level",
		blindsTitle: "Blinds",
		energyNow: "Currently using",
		energyTotal: "Energy used",
		energyToday: "Energy used today",
		batteryThreshold: 20,
    		coThreshold: 650,
		subMenus: true,
		smartMeter: false,
		smartMeterOffset: 0,
		showItems: ['temperature'],   
		excludeDevices: ['Ute_T'],  // Device that will not be shown
		onlyShowExcluded: true, // if true only exluded devices are shown
		textWhite: false,
		alarmOffLabel: "Disabled",
		groupSensors: false
	}
}
```

**Comment by SpoturDeal** [comment]
Could you try to add a not existing device to the array of excludeDevices

```
excludeDevices: ['notadevice','Ute_T'], 
```

**Comment by flopp999** [comment]
Sorry for late response, but it doesn't work even if I add an not existing device

**Comment by 1kohm** [comment]
Hi, 
I have the same issue when"onlyShowExcluded" set to "true" then I see all devices. 
I've tested it also by adding non existing domoticz device to "excludeDevices: ['MQTT Discovery - Salon_Żarówka_01','notexist']," like you aksed but with no result. 

My config:

> {
                        module: "MMM-Domoticz",
                        position: "top_right",   // see mirror setting for options
                        config: {
					updateInterval: 30,                          // every 45 seconds
        			apiBase: '10.10.0.110',                   // the IPaddress of you Domoticz HC in your home network
        			apiPort: 8080,                               // just leave at 80
			        moduleTitle: "smart house",   
        			temperatureTitle:"Aktualna temperatura",     // You can adapt the following text to fit your language
        			energyTitle: "Energy used by",               // The tile for the energy use part
        			batteryTitle: "Battery level",
        			blindsTitle:  "Blinds",
        			voltageTitle: "Voltage/Current",
        			alarmTitle: "Alarm system",
        			alarmLabel: "Current alarm status",
        			pulseLabel: "Pulse meters",
        			rainLabel: "Rain",
        			coTitle: "CO2 level",
        			sensorTitle: "Window/Door sensors",
        			energyNow: "Currently",                      // Label to show current use
        			energyTotal: "Total used",                   // Label for total registred energy used
        			energyToday: "Today used",                   // Label for energy used today
        			energyMeter1: "kWh meter I",
        			energyMeter2: "kWh meter II",
        			gasTotal: "Total used gas",                   // Label for total registred gas used
        			gasToday: "Today used gas",                   // Label for gas used today
        			waterTotal: "Total used H2O",                   // Label for total registred water used
        			waterToday: "Today used H2O",                   // Label for water used today
        			showItems: ['meter','battery','co','baro','alarm','temperature','energy','blinds','humidity','voltage','sensor','pulse','rain'],
        			alarmOffLabel: "Security Disarmed",
        			alarmOnLabel: "Security Armed",
        			smartMeter: true,
        			smartMeterOffset: 0,
        			smartMeterGasOffset: 1000,
        			smartMeterWaterOffset: 1000,
        			batteryThreshold: 15,                        // if lower then threshold show
        			coThreshold: 100,                            // if higher then threshold show
        			subMenus: true,                             // true or false
        			excludeDevices: ['MQTT Discovery - Salon_Żarówka_01','notexist'],                    // Devices you don`t want to see
        			onlyShowExcluded: true,                     // Only show the excluded devices
        			textWhite: true,
        			groupSensors:true                           // group the data from a single Sensor
			}
		},

looking forward your comments

**Comment by SpoturDeal** [comment]
@flopp999 
I have stopped using Domoticz a few months ago.
Switched over to OpenHAB which is more flexible.

It takes time to change modules, that time I don't have right now. 
Someone else already made a new version of the Domoticz module.
