### ISSUE TITLE
Device not hidden

### ISSUE THREAD

**Issue by jacobhallgren** [SpoturDeal/MMM-Domoticz#2]
Does not work to set a device in hidden section config.js.

Works if i do it in the file MMM-Domoticz.js

**Comment by SpoturDeal** [comment]
The device name is case sensitive?

please give some more info so I can check

**Comment by jacobhallgren** [comment]
Yes I know its case senistive, but if i type the exact same name "Brevlåda" och "spottar" in config.js it doesent hide the device. But works like a charm if I do it in the file MMM-Domoticz.js

**Comment by SpoturDeal** [comment]
This error has been fixed in the example config was an error
exclude**d**Devices  should be excludeDevices
