### ISSUE TITLE
Battery items are never displayed

### ISSUE THREAD

**Issue by BlackCatDeployment** [SpoturDeal/MMM-Domoticz#20]
Even if I see BatteryLevel param in the Domoticz API JSON output:
Example:
...
`"AddjMulti": 1,
"AddjMulti2": 1,
"AddjValue": 0,
"AddjValue2": 0,
"BatteryLevel": 76,
"HardwareID": 5,
"HardwareName": "Netatmo",
"HardwareType": "Netatmo",
"HardwareTypeVal": 54,
"HaveTimeout": false,
"LastUpdate": "2019-09-09 00:30:02",
"Name": "Netatmo Batterie",
"Notifications": "false",`
...
And I set _batteryThreshold: 100_ and _showItems: ['temperature', 'battery']_ in my config.js, I never see it on MagicMirror.
Temperature gets from Netatmo correctly displayed.

I checked the code and didn't find what's wrong :(

Am I alone?

**Comment by SpoturDeal** [comment]
@BlackCatDeployment 
I have stopped using Domoticz a few months ago.
Switched over to OpenHAB which is more flexible.

It takes time to change modules, that time I don't have right now. 
Someone else already made a new version of the Domoticz module.
