### ISSUE TITLE
How does icons works?

### ISSUE THREAD

**Issue by 1kohm** [SpoturDeal/MMM-Domoticz#22]
Hi, 
I'm wondering how does the icons works and where I can define icon type. 
For example I have device "Gniazko C" and device "Salon - Zasilanie". In both case in Domoticz "Switch Type: On/Off " but Icons are different. 

![image](https://user-images.githubusercontent.com/16636275/71851226-5aa32f80-30d6-11ea-9d33-1b5beab192d4.png)

Does the plugin take it form device type or other setting?

**Comment by SpoturDeal** [comment]
@1kohm 
I have stopped using Domoticz a few months ago.
Switched over to OpenHAB which is more flexible.

It takes time to change modules, _that time I don't have right now._ 
Someone else already made a new version of the Domoticz module.
