### ISSUE TITLE
Display flashes

### ISSUE THREAD

**Issue by Doudy** [SpoturDeal/MMM-Domoticz#23]
Display flashes every 2 to 3 seconds
Flashes: text appears and disappears!

**Comment by SpoturDeal** [comment]
@Doudy 
I have stopped using Domoticz a few months ago.
Switched over to OpenHAB which is more flexible.

It takes time to change modules, that time I don't have right now.
Someone else already made a new version of the Domoticz module.

**Comment by Doudy** [comment]
OK thanks
