### ISSUE TITLE
Organize probes

### ISSUE THREAD

**Issue by mattx38** [SpoturDeal/MMM-Domoticz#24]
Hello,

Firestable, I want to thank you for your excellent developement. I'm very glad of it.
What I ask here is not due to an issue but a need.

I would like to organize the probes by names or even in other spefic or order.
How can I do this ?

Thank you

**Comment by SpoturDeal** [comment]
I have stopped using Domoticz and switched over to OpenHAB.
Because of this reason I am not able to make any changes to the application.
