### ISSUE TITLE
Format Domoticz on Magic mirror

### ISSUE THREAD

**Issue by erikmoust** [SpoturDeal/MMM-Domoticz#25]
Hi, is it possible to format the output from MMM-Domoticz?
I now have small and big fonts.
<img width="1111" alt="Schermafbeelding 2020-12-03 om 11 06 27" src="https://user-images.githubusercontent.com/75415089/100995203-c2b4fc80-3557-11eb-8f8e-7ec66d23d2b2.png">

**Comment by SpoturDeal** [comment]
I am not able to update or make any changes to this module at the moment.
About 16 months ago I changed from Domoticz to OpenHAB and I am not able to give further assistance on this module.
